# Generated by Django 5.2.6 on 2025-11-23 20:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satisfaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersatisfaction',
            name='rating',
            field=models.DecimalField(choices=[(Decimal('1.0'), '1.0'), (Decimal('1.5'), '1.5'), (Decimal('2.0'), '2.0'), (Decimal('2.5'), '2.5'), (Decimal('3.0'), '3.0'), (Decimal('3.5'), '3.5'), (Decimal('4.0'), '4.0'), (Decimal('4.5'), '4.5'), (Decimal('5.0'), '5.0')], decimal_places=1, help_text='Calificación del cliente (1.0 a 5.0)', max_digits=3),
        ),
    ]
