# Generated by Django 5.2.6 on 2025-11-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('abierto', 'Abierto'), ('en_curso', 'En curso'), ('cerrado', 'Cerrado'), ('en_espera', 'En espera')], default='en_espera', max_length=20),
        ),
    ]
